django/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


MEDIA_FILE_PATHS = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls',)),
    path('', include('core.urls', )),

] + MEDIA_FILE_PATHS

django/core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('movies/<int:movie_id>/image/upload/', views.MovieImageUpload.as_view(), name='MovieImageUpload'),
    path('movies/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movies/<int:movie_id>/vote/', views.CreateVote.as_view(), name='CreateVote'),
    path('movies/<int:pk>/', views.MovieDetail.as_view(), name='MovieDetail'),
    path('movies/top/', views.TopMovies.as_view(), name='TopMovies'),
    path('movies/', views.MovieList.as_view(), name='MovieList'),

]

django/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

django/templates/base.html
<!DOCTYPE html>
<html lang="ru" >
<head>
  <meta charset="UTF-8" >
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  >
  <link
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    rel="stylesheet"
    crossorigin="anonymous"
  >
  <title>
    {% block title %}MyMDB{% endblock %}
  </title>
  <style>
    .mymdb-masthead {
      background-color: #EEEEEE;
      margin-bottom: 1em;
    }
  </style>

</head>
  <body>
    <div class="mymdb-masthead">
      <div class="container">
        <nav class="navbar">
          <div class="navbar-brand">MyMDB</div>
          <div class="navbar mr-auto">
            <div class="navbar-item">
              <a class="navbar-link" href="{% url 'core:MovieList' %}"> Movies | </a>
              <a class="navbar-link" href="{% url 'core:TopMovies' %}"> TOP 10 MOVIES | </a>
            </div>
          </div>
          <div class="navbar ml-auto">
            {% if request.user.is_authenticated %}
            <a class="navbar-link" href="{% url 'user:logout' %}"> Log out </a>
            {% else %}
            <div class="navbar-item">
              <a class="navbar-link" href="{% url 'user:login' %}"> Login </a>
              <a class="navbar-link" href="{% url 'user:register' %}"> Register </a>
            </div>
            {% endif %} 
          </div>
        </nav>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 mymdb-main">
         {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
          {% block sidebar %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>